// Code generated by go-swagger; DO NOT EDIT.

package metadaservices

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// ApisHandlerFunc turns a function with the right signature into a apis handler
type ApisHandlerFunc func(ApisParams) middleware.Responder

// Handle executing the request and returning a response
func (fn ApisHandlerFunc) Handle(params ApisParams) middleware.Responder {
	return fn(params)
}

// ApisHandler interface for that can handle valid apis params
type ApisHandler interface {
	Handle(ApisParams) middleware.Responder
}

// NewApis creates a new http.Handler for the apis operation
func NewApis(ctx *middleware.Context, handler ApisHandler) *Apis {
	return &Apis{Context: ctx, Handler: handler}
}

/*Apis swagger:route GET /apis metadaservices apis

Apis apis API

*/
type Apis struct {
	Context *middleware.Context
	Handler ApisHandler
}

func (o *Apis) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewApisParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
