// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi The API dictory list
This is an API service to list all service metatdata that can be used in a place it contains


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.0.1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
